#!/bin/bash

echo "###### Running Tests ######"

# shellcheck disable=SC1090
source ~/.bashrc

cd "$(dirname ${BASH_SOURCE[0]})" && cd ../

if [[ -n "$JDK17" ]]; then
  export JAVA_HOME=$JDK17
fi

./gradlew clean test
TEST_STATUS=$?

if [ $TEST_STATUS  -eq 0 ]; then
  echo "Test has successfully completed"
  exit 0
else
  echo "Failed to test"
  exit 1
fi


./gradlew clean test
