spring:
  datasource:
    url: jdbc:mysql://localhost:3306/muin_music
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: muin_music
    password: muin1234!

  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
