spring:
  datasource:
    url: jdbc:mysql://43.202.56.183:3306/muin_music
    username: muin_music
    password: muin1234!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
